export const INDIAN_STOCKS = [
  { symbol: 'TCS',          name: 'Tata Consultancy Services',         sector: 'Information Technology' },
  { symbol: 'INFY',         name: 'Infosys',                           sector: 'Information Technology' },
  { symbol: 'RELIANCE',     name: 'Reliance Industries',               sector: 'Energy & Petrochemicals' },
  { symbol: 'HDFCBANK',     name: 'HDFC Bank',                         sector: 'Banking & Finance' },
  { symbol: 'ICICIBANK',    name: 'ICICI Bank',                        sector: 'Banking & Finance' },
  { symbol: 'AXISBANK',     name: 'Axis Bank',                         sector: 'Banking & Finance' },
  { symbol: 'BAJAJFINSV',   name: 'Bajaj Finserv',                     sector: 'Banking & Finance' },
  { symbol: 'BAJFINANCE',   name: 'Bajaj Finance',                     sector: 'Banking & Finance' },
  { symbol: 'MARUTI',       name: 'Maruti Suzuki',                     sector: 'Automobile' },
  { symbol: 'SBIN',         name: 'State Bank of India',               sector: 'Banking & Finance' },
  { symbol: 'WIPRO',        name: 'Wipro',                             sector: 'Information Technology' },
  { symbol: 'HCLTECH',      name: 'HCL Technologies',                  sector: 'Information Technology' },
  { symbol: 'TECHM',        name: 'Tech Mahindra',                     sector: 'Information Technology' },
  { symbol: 'LT',           name: 'Larsen & Toubro',                   sector: 'Infrastructure' },
  { symbol: 'ITC',          name: 'ITC Limited',                       sector: 'FMCG' },
  { symbol: 'SUNPHARMA',    name: 'Sun Pharmaceutical',                sector: 'Pharmaceuticals' },
  { symbol: 'DMART',        name: 'Avenue Supermarts (DMart)',          sector: 'Retail' },
  { symbol: 'NESTLEIND',    name: 'Nestle India',                      sector: 'FMCG' },
  { symbol: 'ADANIPORTS',   name: 'Adani Ports and SEZ',               sector: 'Infrastructure' },
  { symbol: 'BHARTIARTL',   name: 'Bharti Airtel',                     sector: 'Telecom' },
  { symbol: 'JSWSTEEL',     name: 'JSW Steel',                         sector: 'Metals & Mining' },
  { symbol: 'TATASTEEL',    name: 'Tata Steel',                        sector: 'Metals & Mining' },
  { symbol: 'TATAMOTORS',   name: 'Tata Motors',                       sector: 'Automobile' },
  { symbol: 'M&M',          name: 'Mahindra & Mahindra',               sector: 'Automobile' },
  { symbol: 'HINDUNILVR',   name: 'Hindustan Unilever',                sector: 'FMCG' },
  { symbol: 'KOTAKBANK',    name: 'Kotak Mahindra Bank',               sector: 'Banking & Finance' },
  { symbol: 'INDUSINDBK',   name: 'IndusInd Bank',                     sector: 'Banking & Finance' },
  { symbol: 'ASIANPAINT',   name: 'Asian Paints',                      sector: 'Consumer Goods' },
  { symbol: 'ULTRACEMCO',   name: 'UltraTech Cement',                  sector: 'Cement' },
  { symbol: 'TITAN',        name: 'Titan Company',                     sector: 'Consumer Goods' },
  { symbol: 'POWERGRID',    name: 'Power Grid Corporation',            sector: 'Power' },
  { symbol: 'NTPC',         name: 'NTPC Limited',                      sector: 'Power' },
  { symbol: 'ONGC',         name: 'Oil & Natural Gas Corporation',     sector: 'Energy & Petrochemicals' },
  { symbol: 'COALINDIA',    name: 'Coal India',                        sector: 'Mining' },
  { symbol: 'BPCL',         name: 'Bharat Petroleum Corporation',      sector: 'Energy & Petrochemicals' },
  { symbol: 'IOC',          name: 'Indian Oil Corporation',            sector: 'Energy & Petrochemicals' },
  { symbol: 'GAIL',         name: 'GAIL (India)',                      sector: 'Energy & Petrochemicals' },
  { symbol: 'CIPLA',        name: 'Cipla',                             sector: 'Pharmaceuticals' },
  { symbol: 'DRREDDY',      name: "Dr. Reddy's Laboratories",          sector: 'Pharmaceuticals' },
  { symbol: 'DIVISLAB',     name: "Divi's Laboratories",               sector: 'Pharmaceuticals' },
  { symbol: 'APOLLOHOSP',   name: 'Apollo Hospitals Enterprise',       sector: 'Healthcare' },
  { symbol: 'NATCOPHARM',   name: 'Natco Pharma Limited',              sector: 'Pharmaceuticals' },
  { symbol: 'LUPIN',        name: 'Lupin Limited',                     sector: 'Pharmaceuticals' },
  { symbol: 'AUROPHARMA',   name: 'Aurobindo Pharma',                  sector: 'Pharmaceuticals' },
  { symbol: 'BIOCON',       name: 'Biocon',                            sector: 'Pharmaceuticals' },
  { symbol: 'TORNTPHARM',   name: 'Torrent Pharmaceuticals',           sector: 'Pharmaceuticals' },
  { symbol: 'ZYDUSLIFE',    name: 'Zydus Lifesciences',                sector: 'Pharmaceuticals' },
  { symbol: 'ALKEM',        name: 'Alkem Laboratories',                sector: 'Pharmaceuticals' },
  { symbol: 'GLAND',        name: 'Gland Pharma',                      sector: 'Pharmaceuticals' },
  { symbol: 'ABBOTINDIA',   name: 'Abbott India',                      sector: 'Pharmaceuticals' },
  { symbol: 'EICHERMOT',    name: 'Eicher Motors',                     sector: 'Automobile' },
  { symbol: 'BAJAJ-AUTO',   name: 'Bajaj Auto',                        sector: 'Automobile' },
  { symbol: 'HEROMOTOCO',   name: 'Hero MotoCorp',                     sector: 'Automobile' },
  { symbol: 'TATAPOWER',    name: 'Tata Power Company',                sector: 'Power' },
  { symbol: 'ADANIENT',     name: 'Adani Enterprises',                 sector: 'Conglomerate' },
  { symbol: 'ADANIGREEN',   name: 'Adani Green Energy',                sector: 'Power' },
  { symbol: 'VEDL',         name: 'Vedanta Limited',                   sector: 'Metals & Mining' },
  { symbol: 'HINDALCO',     name: 'Hindalco Industries',               sector: 'Metals & Mining' },
  { symbol: 'SAIL',         name: 'Steel Authority of India',          sector: 'Metals & Mining' },
  { symbol: 'NMDC',         name: 'NMDC Limited',                      sector: 'Mining' },
  { symbol: 'GODREJCP',     name: 'Godrej Consumer Products',          sector: 'FMCG' },
  { symbol: 'MARICO',       name: 'Marico',                            sector: 'FMCG' },
  { symbol: 'DABUR',        name: 'Dabur India',                       sector: 'FMCG' },
  { symbol: 'COLPAL',       name: 'Colgate-Palmolive India',           sector: 'FMCG' },
  { symbol: 'BRITANNIA',    name: 'Britannia Industries',              sector: 'FMCG' },
  { symbol: 'TATACONSUM',   name: 'Tata Consumer Products',            sector: 'FMCG' },
  { symbol: 'PIDILITIND',   name: 'Pidilite Industries',               sector: 'Consumer Goods' },
  { symbol: 'BERGEPAINT',   name: 'Berger Paints India',               sector: 'Consumer Goods' },
  { symbol: 'HAVELLS',      name: 'Havells India',                     sector: 'Consumer Goods' },
  { symbol: 'ZOMATO',       name: 'Zomato',                            sector: 'Technology' },
  { symbol: 'NYKAA',        name: 'FSN E-Commerce (Nykaa)',            sector: 'Technology' },
  { symbol: 'PAYTM',        name: 'One97 Communications (Paytm)',      sector: 'Technology' },
  { symbol: 'IRCTC',        name: 'Indian Railway Catering & Tourism', sector: 'Travel & Tourism' },
  { symbol: 'INDIGO',       name: 'InterGlobe Aviation (IndiGo)',      sector: 'Aviation' },
  { symbol: 'MUTHOOTFIN',   name: 'Muthoot Finance',                   sector: 'Banking & Finance' },
  { symbol: 'CHOLAFIN',     name: 'Cholamandalam Investment',          sector: 'Banking & Finance' },
  { symbol: 'HDFCLIFE',     name: 'HDFC Life Insurance',               sector: 'Insurance' },
  { symbol: 'SBILIFE',      name: 'SBI Life Insurance',                sector: 'Insurance' },
  { symbol: 'ICICIPRULI',   name: 'ICICI Prudential Life Insurance',   sector: 'Insurance' },
  { symbol: 'DELHIVERY',    name: 'Delhivery',                         sector: 'Logistics' },
  { symbol: 'LTIM',         name: 'LTIMindtree',                       sector: 'Information Technology' },
  { symbol: 'MPHASIS',      name: 'Mphasis',                           sector: 'Information Technology' },
  { symbol: 'PERSISTENT',   name: 'Persistent Systems',                sector: 'Information Technology' },
  { symbol: 'COFORGE',      name: 'Coforge',                           sector: 'Information Technology' },
  { symbol: 'TATAELXSI',    name: 'Tata Elxsi',                        sector: 'Information Technology' },
  { symbol: 'SIEMENS',      name: 'Siemens India',                     sector: 'Capital Goods' },
  { symbol: 'ABB',          name: 'ABB India',                         sector: 'Capital Goods' },
  { symbol: 'BHEL',         name: 'Bharat Heavy Electricals',          sector: 'Capital Goods' },
  { symbol: 'BEL',          name: 'Bharat Electronics',                sector: 'Defence' },
  { symbol: 'HAL',          name: 'Hindustan Aeronautics',             sector: 'Defence' },
  { symbol: 'CONCOR',       name: 'Container Corporation of India',    sector: 'Logistics' },
  { symbol: 'POLYCAB',      name: 'Polycab India',                     sector: 'Capital Goods' },
  { symbol: 'DIXON',        name: 'Dixon Technologies',                sector: 'Consumer Goods' },
  { symbol: 'BATAINDIA',    name: 'Bata India',                        sector: 'Consumer Goods' },
  { symbol: 'VBL',          name: 'Varun Beverages',                   sector: 'FMCG' },
  { symbol: 'METROPOLIS',   name: 'Metropolis Healthcare',             sector: 'Healthcare' },
  { symbol: 'LALPATHLAB',   name: 'Dr Lal PathLabs',                   sector: 'Healthcare' },
  { symbol: 'MAXHEALTH',    name: 'Max Healthcare Institute',          sector: 'Healthcare' },
  { symbol: 'FORTIS',       name: 'Fortis Healthcare',                 sector: 'Healthcare' },
  { symbol: 'NH',           name: 'Narayana Hrudayalaya',              sector: 'Healthcare' },
  { symbol: 'PIIND',        name: 'PI Industries',                     sector: 'Agrochemicals' },
  { symbol: 'UPL',          name: 'UPL Limited',                       sector: 'Agrochemicals' },
  { symbol: 'SRF',          name: 'SRF Limited',                       sector: 'Chemicals' },
];

export const MAX_SEARCH_HISTORY = 5;
export const SEARCH_HISTORY_KEY = 'stock_search_history';
export const DARK_MODE_KEY = 'dark_mode';
